### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by yuanzhihai** [QThans/thinkphp-filesystem-cloud#2]
\think\Facade\Filesystem::getDiskConfig('public', 'url') 使用这个方法报错了，
没安装这个扩展 本地上传是没问题的 影响了本地上传

**Comment by yuanzhihai** [comment]
需要在 thans\filesystem\Filesystem 添加以下方法
/**
* 获取缓存配置
* @access public
* @param null|string $name 名称
* @param mixed $default 默认值
* @return mixed
*/
public function getConfig(string $name = null, $default = null)
{
if (!is_null($name)) {
return $this->app->config->get('filesystem.' . $name, $default);
}

    return $this->app->config->get('filesystem');
}

/**
 * 获取磁盘配置
 * @param string $disk
 * @param null   $name
 * @param null   $default
 * @return array
 */
public function getDiskConfig($disk, $name = null, $default = null)
{
    if ($config = $this->getConfig("disks.{$disk}")) {
        return Arr::get($config, $name, $default);
    }

    throw new InvalidArgumentException("Disk [$disk] not found.");
}

**Comment by QThans** [comment]
你可以提交下pr 我晚上看下

**Comment by QThans** [comment]
已合并 #3
